### ISSUE TITLE
Crash if 0 detection present

### ISSUE THREAD

**Issue by firesharker** [nwojke/mcf-tracker#1]
The `ObservationCostModel`'s `compute_cost` method doesn't handle the edge case if `detector_confidence_scores` is empty.

**Comment by nwojke** [comment]
Thanks, should be fixed now ([c1c8fff](https://github.com/nwojke/mcf-tracker/commit/c1c8ffff0afc41c38c5e37bb76aeeccc3522699a)).

**Comment by firesharker** [comment]
Thanks!
