### ISSUE TITLE
Transition Costs

### ISSUE THREAD

**Issue by filipetrocadoferreira** [nwojke/mcf-tracker#3]
I'm testing the tracker with a simpler transition model. It is simply euclidean distance between points. The goal of tracker is to minimize the cost right (this means, the euclidean distance between points of trajectory) however this simple approach does not output any result

**Comment by nwojke** [comment]
In short, you need to set a negative observation cost. Have a look at [1] for information on the probabilstic model.

[1] Zhang, L., Li, Y., & Nevatia, R. (2008). Global data association for multi-object tracking using network flows. In IEEE Conference on Computer Vision and Pattern Recognition (pp. 1-8).

**Comment by nwojke** [comment]
Closing this one for now. You may re-open if your issue cannot be resolved.
