### ISSUE TITLE
Question about EOM (Explicit Occlusion Model) approach

### ISSUE THREAD

**Issue by ahyunSeo** [nwojke/mcf-tracker#6]
Hello

I read the article  Global Data Association for Multi-Object Tracking Using Network Flows,

and now I wonder if there's EOM (Explicit Occlusion Model) approach is used in this repo,

I tried to find the part but I couldn't. 

Is this tracker only solve naive min-cost flow?

Please tell me whether the EOM approach is included and if yes, 

I would appreciate if you tell me where.

Thank you

Ahyun

**Comment by nwojke** [comment]
Hi ahyunSeo,

the explicit occlusion model is not implemented in this code.

All the best

Edit: Closing this one since the question has been answered. You may re-open in case questions remain.
