### ISSUE TITLE
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

### ISSUE THREAD

**Issue by hxtkyne** [nwojke/mcf-tracker#8]
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

when i read model, an problem occur.

**Comment by hxtkyne** [comment]
solved the problem

**Comment by Kinantb** [comment]
@hxtkyne It would be helpful if you would briefly describe how you did that...

**Comment by dimahwang88** [comment]
@hxtkyne how have you solved the problem?

**Comment by dimahwang88** [comment]
python motchallenge_trainer.py --cnn_model resources/networks/mars-small128.pb
solves the problem

**Comment by Kinantb** [comment]
@dimahwang88 This seems to work. Thanks!
